config/routes.rb
Rails.application.routes.draw do
devise_for :users, controller: {sessions: 'users/sessions', registration: 'users/registration'}
root to: 'homes#top'
get 'home/about' => 'homes#about'
get '/search' => 'search#search'
    # ＃url          controller名　アクション名
resources :users, only: [:index,:show, :edit, :update] do
resource :relationships, only: [:create, :destroy]
get 'followings' => 'relationships#followings', as: 'followings'
get 'followers' => 'relationships#followers', as: 'followers'
end
resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
resource :favorites, only: [:create, :destroy]
resources :book_comments, only: [:create, :destroy]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
belongs_to :user
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

def favorited_by?(user)
favorites.where(user_id: user.id).exists?
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
validates :comment, presence: true
belongs_to :user
belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
belongs_to :user
belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
has_many :books, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followings, through: :relationships, source: :followed
attachment :profile_image
def follow(user_id)
  relationships.create(followed_id: user_id)
end
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
def following?(user)
 followings.include?(user)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
def create
@book = Book.find(params[:book_id])
@book_comment = BookComment.new(book_comment_params)
@book_comment.user_id = current_user.id
@book_comment.book_id = @book.id
@user = current_user
@book_comment.save

end

def destroy
@book = Book.find(params[:book_id])
@book_comment = @book.book_comments.find(params[:id])
@book_comment.destroy
# ＃非同期での記述の仕方が不明
end

private
def book_comment_params
params.require(:book_comment).permit(:comment)
end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]
  def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  @user = current_user
  if @book.save
  flash[:key] = 'You have created book successfully.'
  redirect_to book_path(@book.id)
  else
  # flash[:error] = "error"
  @books=Book.all
  render 'index'
  end
  end


  def index
  @books = Book.all
  @book = Book.new
  @user = current_user
  end

  def show
  @book = Book.find(params[:id])
  @book_new = Book.new
  @user = @book.user
  @book_comment = BookComment.new
  end

  def edit
  @book = Book.find(params[:id])
  end
  def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
  flash[:key] = 'You have updated book successfully.'
  redirect_to book_path(@book.id)
  else
  render 'edit'
  end
  end

  def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def ensure_correct_user
  @book = Book.find(params[:id])
  unless @book.user == current_user
  redirect_to books_path
  end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
@book = Book.find(params[:book_id])
favorite = current_user.favorites.new(book_id: @book.id)
favorite.save
# ＃redirect_back(fallback_location: root_url)非同期通信では、redirectがあると画面推移してしまうので削除
end
def destroy
@book = Book.find(params[:book_id])
favorite = current_user.favorites.find_by(book_id: @book.id)
favorite.destroy
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
end
def about
end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
def create
 current_user.follow(params[:user_id])
 redirect_to request.referer
end
def destroy
 current_user.unfollow(params[:user_id])
 redirect_to request.referer
end
def followings
 user = User.find(params[:user_id])
 @users = user.followings
end
def followers
 user = User.find(params[:user_id])
 @users = user.followers
end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  @modle = params["search"] ["model"]
  # ＃選択したモデルを@modleに代入
  @value = params["search"] ["value"]
  # ＃検索にかけた文字列を@valueに代入
  @how = params["search"] ["how"]
  # ＃検索した検索方法を＠howに代入
  @dates = search_for(@how, @modle, @value)
  # ＃search_forの引数にインスタント変数を定義、@datesに最終検索結果が入る
  end

private

def match(modle,value)
  # search＿forでhowがmatchだった場合の処理
  if modle == 'user'
  # ＃modleがuserだった場合の処理
   User.where(name: value)
  # ＃whereで文字列が完全一致する名前を探す
  elsif modle == 'book'
   Book.where(title: value)
  end
end
def forward(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "#{value}%")
              # ＃カラム名　　　　値
  elsif modle == 'book'
    Book.where("title LIKE ?", "#{value}%")
  end
end
def backward(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "%#{value}")
  elsif modle == 'book'
    Book.where("title LIKE ?", "%#{value}")
  end
end
def partical(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "%#{value}%")
  elsif modle == 'book'
    Book.where("title LIKE ?", "%#{value}%")
  end
end
def search_for(how,modle,value)
# ＃searchアクションで定義した情報が引数に入っている
 case how
# ＃検索方法のhowの中身がどれなのかwhenの条件分岐から探す処理
 when 'match'
  match(modle, value)
  # ＃検索方法の引数に（modle、value）
  # ＃例えばhowがmatchならdef matchの処理を行う
 when 'forward'
  forward(modle, value)
 when 'backward'
  backward(modle, value)
 when 'partical'
  partical(modle, value)
 end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user, only:[:edit]
def index
@book = Book.new
@users = User.all
@user = current_user
end
def show
@user = User.find(params[:id])
@books = @user.books
@book = Book.new
end

def edit
@user = User.find(params[:id])
end

def update
@user = User.find(params[:id])
flash[:key] = 'You have updated user successfully.'
if @user.update(user_params)
redirect_to user_path(@user.id)
else
render :edit
end
end



private
def user_params
params.require(:user).permit(:name, :introduction, :profile_image)
end
def ensure_correct_user
@user = User.find(params[:id])
unless @user == current_user
redirect_to user_path(current_user.id)
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
コメント数:<%= book.book_comments.count %>
<% book.book_comments.each do |book_comment| %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <%= book_comment.user.name %>
           <%= book_comment.comment %>
       <% if user == current_user %>
       <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote: true, "data-confirm" => "本当に消しますか?" %>
      <% end %>
    <% end %>
<%= form_with(model:[book,book_comment],remote: true) do |f| %>
<%= f.text_area :comment %>
<%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
document.getElementById('book_comment_<%= @book.id %>').innerHTML = '<%= escape_javascript(render "book_comments/book_comments", book: @book, user: @user, book_comment: @book_comment) %>'
$("#book_comment_comment").val("");
<!--＃値を残さない、他に記述の方法は？-->

app/views/book_comments/destroy.js.erb
document.getElementById('book_comment_<%= @book.id %>').innerHTML = '<%= escape_javascript(render "book_comments/book_comments", book: @book, user: @user, book_comment: @book_comment) %>'
$("#book_comment_comment").val("");

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
<div class="form-group">
<lavel for="book_title">Title</lavel>
<%= f.text_field :title %>
</div>
<div class="form-group">
<lavel for="book_opinion">Opinion</lavel>
<%= f.text_area :body %>
</div>
<div class="form-group">
<%= f.submit 'Update Book' %>
</div>
<%= link_to "Show", book_path(@book.id) %>
  |

<%= link_to "Back", books_path %>
<% end %>
</div>
</div>
</div>

app/views/books/index.html.erb
<%= flash[:key] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<main>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= link_to user_path(current_user.id) do %>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<% end %>
<table class="table">
<tbody>
<tr>
<th>name</th>
<th><%= @user.name %></th>
</tr>
<tr>
<th>introduction</th>
<th><%= @user.introduction %></th>
</tr>
<tr>
  <th>follows</th>
<th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
</tr>
<tr>
  <th>followers</th>
 <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
</tr>
<tr>
<% if current_user != @user %>
 <!--#どういう意味？-->
　<% if current_user.following?(@user) %>
  <!--#引数で渡したユーザーをフォローしているか判断している-->
    <%= link_to "フォローを外す", user_relationships_path(@user), method: :delete %>
    <!--＃すでにフォローしている相手-->
  <% else %>
    <%= link_to "フォローする", user_relationships_path(@user), method: :post %>
  　<!--＃まだフォローしていない相手-->
  <% end %>
<% end %>
</tr>
</tbody>
</table>

<div ="row">
<p><%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></p>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <!--<lavel for="book_body">Opinion</lavel>-->
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f. submit 'Create Book' %>
  </div>
<% end %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-hover table-inverse">
<thead>
<tr>
<th></th>
<th>Title</th>
<th>Opinion</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td><%= link_to user_path(book.user) do %>
<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<% end %></td>
<td>
<%= link_to book.title, book_path(book.id) %>
</td>
<td><%= book.body %></td>
<td><%=  "#{book.book_comments.count} コメント" %></td>
<td id="favorite_<%= book.id %>">
<!--＃＠bookでどの本かを指定　仮に本のidが１の時にid属性は、favorite1になる-->
<%= render 'favorites/favorites', book: book %>
</td>
<% end %>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</main>

app/views/books/new.html.erb
<h2>New book</h2>
<!--<%= flash[:error] %>-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>



<%= form_with model: @book, url:'/books', local:true do |f| %>
   
  <div class="field">
  <lavel for="book_title">Title</lavel>
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <lavel for="book_body">Body</lavel>
  <%= f.text_area :body %>
  </div>
  <div class="actions">
  <%= f. submit 'Create Book' %>
  </div>
<% end %>

app/views/books/show.html.erb
<%= flash[:key] %>
<main>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
<h2>User info</h2>
     <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">
 <tbody>
 <tr>
  <th>name</th>
   <th><%= @user.name %></th>
 </tr>
 <tr>
   <th>introduction</th>
   <th><%= @user.introduction %></th>
 </tr>
 <tr>
  <th>follows</th>
<th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
</tr>
<tr>
  <th>followers</th>
 <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
</tr>
 </tbody>
</table>
<tr>
<% if current_user != @user %>
 <!--#どういう意味？ログインしているユーザーが違うとき-->
　<% if current_user.following?(@user) %>
  <!--#引数で渡したユーザーをフォローしているか判断している-->
    <%= link_to "フォローを外す", user_relationships_path(@user), method: :delete %>
    <!--＃すでにフォローしている相手-->
  <% else %>
    <%= link_to "フォローする", user_relationships_path(@user), method: :post %>
  　<!--＃まだフォローしていない相手-->
  <% end %>
<% end %>
</tr>
<div ="row">
<p><%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></p>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book_new, url:'/books', local:true do |f| %>
  <div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <!--<lavel for="book_body">Opinion</lavel>-->
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f. submit 'Create Book' %>
  </div>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class=table>
<tbody>
<tr>
<td><%= link_to user_path(@book.user) do %>
<%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<% end %></td>
<td>
<%= link_to @user.name, user_path(@book.user) %>
</td>
<td><%= link_to @book.title, book_path(@book.id) %></td>
<td><%= @book.body %></td>
<td><% if @user == current_user %>
<%= link_to "Edit", edit_book_path(@book.id) %></td>
<% end %>
<td><% if @user == current_user %>
<%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?" %>
<% end %>
</td>
<td id="book_comment_<%= @book.id %>">
<%= render 'book_comments/book_comments', book: @book, user: @user, book_comment: @book_comment %>
</td>
<td id="favorite_<%= @book.id %>">
<!--＃＠bookでどの本かを指定　仮に本のidが１の時にid属性は、favorite1になる-->
<%= render 'favorites/favorites', book: @book %>
</td>
</td>
</td>
</td>
<tr>
</tbody>
</table>
</div>
</div>
</div>
</main>

app/views/favorites/_favorites.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book.id),method: :delete, remote: true do %>
     <!--＃remote: true非同期通信-->
      ♥<%= book.favorites.count %>
    <% end %>
  
  <% else %>
    <%= link_to book_favorites_path(book.id),method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/favorites/create.js.erb
<!--＃alert('いいねが押せている！');-->
<!--＃アラートが表示できるかの確認-->
<%# app/views/likes/create.js.erb %>
document.getElementById('favorite_<%= @book.id %>').innerHTML = '<%= escape_javascript(render "favorites/favorites", book: @book) %>'

app/views/favorites/destroy.js.erb
<!--＃alert('いいねを解除できている!');  -->
<!--＃アラートが表示できるかの確認-->
<%# app/views/likes/create.js.erb %>
document.getElementById('favorite_<%= @book.id %>').innerHTML = '<%= escape_javascript(render "favorites/favorites", book: @book) %>'

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<main>
<div class="container">
<div class="row">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1> welcome to <i class="fas fa-book"></i>
    <strong>Bookers</strong> !!
</h1>
<p> In <i class="fas fa-book"></i>
<strong>Bookers</strong> , 
</p>
<p>you can share and exchange  your opinions , inpressions , and emotions</p>
<p> about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
<div class="row">
<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
</div>
<div class="row">
<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
</div>
</div>
</div>
    
</div>
    
</div>
</div>
</main>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<!--＃どういう意味？-->
 <% @users.each do |user| %>
<tr>
<td>image</td>
<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
<td>name</td>
<td>
<%= user.name %>
</td>
<td>フォロー数: <%= user.followings.count %></td>
<td>フォロワー数: <%= user.followers.count %></td>
<td>
<%= link_to "Show", user_path(user.id) %>
</td>
<% end %>
</tr>
<% else %>
<%= "ユーザーはいません" %>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<!--＃どういう意味？-->
 <% @users.each do |user| %>
<tr>
<td>image</td>
<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
<td>name</td>
<td>
<%= user.name %>
</td>
<td>フォロー数: <%= user.followings.count %></td>
<td>フォロワー数: <%= user.followers.count %></td>
<td>
<%= link_to "Show", user_path(user.id) %>
</td>
<% end %>
</tr>
<% else %>
<%= "ユーザーはいません" %>
<% end %>

app/views/search/search.html.erb
<% if @modle == "user" %>
<!--＃検索モデルがuserなら-->
<h2>Users search for '<%= @value %>'</h2>
 <tr>
  <th>Name</th>
  <th>Introduction</th>
 </tr>
 <% @dates.each do |user| %>
 <!--#@datesで最終結果を出力-->
  <tr>
   <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></th>
   <th><%= user.name %></th>
   <th><%= user.introduction %></th>
  </tr>
  <% end %>
<% elsif @modle == "book" %>
<h2>Books search for '<%= @value %>'</h2>
 <tr>
   <th>Title</th>
   <th>Opinion</th>
 </tr>
 <% @dates.each do |book| %>
 <tr>
   <th><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th>
   <th><%= book.title %></th>
   <th><%= book.body %></th>
 </tr>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-mb-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@user, local:true do |f| %>
  <div class="form-group">
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  </div>
  <div class="form-group">
  <label for="inputImage">Image</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
 </div>
 <div class="form-group">
  <label for="inputintroduction">introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputintroduction", placeholder:"自己紹介"%>
  </div>
  <div class="form-group">
  <%= f.submit "Update User" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<%= flash[:key] %>
<main>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">
<tbody>
<tr>
<th>name</th>
<th><%= @user.name %></th>
</tr>
<tr>
<th>introduction</th>
<th><%= @user.introduction %></th>
</tr>
<tr>
<th>follows</th>
<th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
</tr>
<tr>
  <th>followers</th>
 <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
</tr>

</tbody>
</table>
<div ="row">
<p><%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></p>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <!--<lavel for="book_body">Opinion</lavel>-->
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f. submit 'Create Book' %>
  </div>
<% end %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class="table table-hover table-inverse">
<thead>
<tr>
<th>image</th>
<th>name</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
<td>
<%= user.name %>
</td>
<td>フォロー数: <%= user.followings.count %></td>
<td>フォロワー数: <%= user.followers.count %></td>
<td>
<% if current_user != user %>
 <!--#どういう意味？-->
　<% if current_user.following?(user) %>
  <!--#引数で渡したユーザーをフォローしているか判断している-->
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
    <!--＃すでにフォローしている相手-->
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  　<!--＃まだフォローしていない相手-->
  <% end %>
<% end %>
</td>
<td>
<%= link_to "Show", user_path(user.id) %>
</td>
<% end %>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</main>

app/views/users/show.html.erb
<%= flash[:notice] %>
<%= flash[:key] %>
<main>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">
<tbody>
<tr>
<th>name</th>
<th><%= @user.name %></th>
</tr>
<tr>
<th>introduction</th>
<th><%= @user.introduction %></th>
</tr>
<tr>
  <th>follows</th>
<th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
</tr>
<tr>
  <th>followers</th>
 <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
</tr>
 </tbody>
</table>
<tr>
<% if current_user != @user %>
 <!--#どういう意味？-->
　<% if current_user.following?(@user) %>
  <!--#引数で渡したユーザーをフォローしているか判断している-->
    <%= link_to "フォローを外す", user_relationships_path(@user), method: :delete %>
    <!--＃すでにフォローしている相手-->
  <% else %>
    <%= link_to "フォローする", user_relationships_path(@user), method: :post %>
  　<!--＃まだフォローしていない相手-->
  <% end %>
<% end %>
</tr>
<div ="row">
<p><%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></p>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <!--<lavel for="book_body">Opinion</lavel>-->
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f. submit 'Create Book' %>
  </div>
<% end %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-hover table-inverse">
<thead>
<tr>
<th></th>
<th>Title</th>
<th>Opinion</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td><%= link_to user_path(book.user) do %>
<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<% end %></td>
<td>
<%= link_to book.title, book_path(book.id) %>
</td>
<td><%= book.body %></td>
<td><%=  "#{book.book_comments.count} コメント" %></td>
<% end %>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</main>