config/routes.rb
Rails.application.routes.draw do
devise_for :users, controller: {sessions: 'users/sessions', registration: 'users/registration'}
root to: 'homes#top'
get 'home/about' => 'homes#about'
get '/search' => 'search#search'
    # ＃url          controller名　アクション名
resources :users, only: [:index,:show, :edit, :update] do
resource :relationships, only: [:create, :destroy]
get 'followings' => 'relationships#followings', as: 'followings'
get 'followers' => 'relationships#followers', as: 'followers'
end
resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
resource :favorites, only: [:create, :destroy]
resources :book_comments, only: [:create, :destroy]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
belongs_to :user
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

def favorited_by?(user)
favorites.where(user_id: user.id).exists?
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
validates :comment, presence: true
belongs_to :user
belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
belongs_to :user
belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
has_many :books, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followings, through: :relationships, source: :followed
attachment :profile_image
def follow(user_id)
  relationships.create(followed_id: user_id)
end
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
def following?(user)
 followings.include?(user)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]
  def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  @user = current_user
  if @book.save
  flash[:key] = 'You have created book successfully.'
  redirect_to book_path(@book.id)
  else
  # flash[:error] = "error"
  @books=Book.all
  render 'index'
  end
  end


  def index
  @books = Book.all
  @book = Book.new
  @user = current_user
  end

  def show
  @book = Book.find(params[:id])
  @book_new = Book.new
  @user = @book.user
  @book_comment = BookComment.new
  end

  def edit
  @book = Book.find(params[:id])
  end
  def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
  flash[:key] = 'You have updated book successfully.'
  redirect_to book_path(@book.id)
  else
  render 'edit'
  end
  end

  def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def ensure_correct_user
  @book = Book.find(params[:id])
  unless @book.user == current_user
  redirect_to books_path
  end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
@book = Book.find(params[:book_id])
favorite = current_user.favorites.new(book_id: @book.id)
favorite.save
# ＃redirect_back(fallback_location: root_url)非同期通信では、redirectがあると画面推移してしまうので削除
end
def destroy
@book = Book.find(params[:book_id])
favorite = current_user.favorites.find_by(book_id: @book.id)
favorite.destroy
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
end
def about
end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  @modle = params["search"] ["model"]
  # ＃選択したモデルを@modleに代入
  @value = params["search"] ["value"]
  # ＃検索にかけた文字列を@valueに代入
  @how = params["search"] ["how"]
  # ＃検索した検索方法を＠howに代入
  @dates = search_for(@how, @modle, @value)
  # ＃search_forの引数にインスタント変数を定義、@datesに最終検索結果が入る
  end

private

def match(modle,value)
  # search＿forでhowがmatchだった場合の処理
  if modle == 'user'
  # ＃modleがuserだった場合の処理
   User.where(name: value)
  # ＃whereで文字列が完全一致する名前を探す
  elsif modle == 'book'
   Book.where(title: value)
  end
end
def forward(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "#{value}%")
              # ＃カラム名　　　　値
  elsif modle == 'book'
    Book.where("title LIKE ?", "#{value}%")
  end
end
def backward(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "%#{value}")
  elsif modle == 'book'
    Book.where("title LIKE ?", "%#{value}")
  end
end
def partical(modle,value)
  if modle == 'user'
    User.where("name LIKE ?", "%#{value}%")
  elsif modle == 'book'
    Book.where("title LIKE ?", "%#{value}%")
  end
end
def search_for(how,modle,value)
# ＃searchアクションで定義した情報が引数に入っている
 case how
# ＃検索方法のhowの中身がどれなのかwhenの条件分岐から探す処理
 when 'match'
  match(modle, value)
  # ＃検索方法の引数に（modle、value）
  # ＃例えばhowがmatchならdef matchの処理を行う
 when 'forward'
  forward(modle, value)
 when 'backward'
  backward(modle, value)
 when 'partical'
  partical(modle, value)
 end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user, only:[:edit]
def index
@book = Book.new
@users = User.all
@user = current_user
end
def show
@user = User.find(params[:id])
@books = @user.books
@book = Book.new
end

def edit
@user = User.find(params[:id])
end

def update
@user = User.find(params[:id])
flash[:key] = 'You have updated user successfully.'
if @user.update(user_params)
redirect_to user_path(@user.id)
else
render :edit
end
end



private
def user_params
params.require(:user).permit(:name, :introduction, :profile_image)
end
def ensure_correct_user
@user = User.find(params[:id])
unless @user == current_user
redirect_to user_path(current_user.id)
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2e6ca6568e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="/">
  <span>Bookers</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
  <% if user_signed_in? %>
  <!--＃userがsign_inしているかの確認、していればelseより上してなければ下(devise側のメゾット)-->
  <li class="navitem">
  <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
  </li>
  <li class="navitem">
  <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
  </li>
  <li class="navitem">
  <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
  </li>
  <li class="navitem">
  <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
  </li>
  <%= form_with url:search_path, method: :get, local: true do |f| %>
  <!--＃参照先URL, 閲覧のみ, ？-->
  <%= f.text_field 'search[value]' %>
  <!--＃？-->
  <%= f.select 'search[model]', options_for_select({"User" => "user", "Book" => "book"}) %>
  <!--＃f.selectとoptions_for_selectでプルダウンが可能になる、search[model]で探すのはモデル、User検索表示名userモデル名を指定-->
  <%= f.select 'search[how]', options_for_select({"完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
  <!--＃表示名＝＞変数-->
  <%= f.submit "検索" %>
  <% end %>
  <% else %>

  <!--<header class="shadow-sm">-->
  <!--<nav class="navbar navbar-expand-lg navbar-light">-->
  <!--<div class="container">-->
  <!--<a class="navbar-brand" href="/">-->
  <!--<span>Bookers</span>-->
  <!--</a>-->
  <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
  <!--<span class="navbar-toggler-icon"></span>-->
  <!--</button>-->
  <!--<div class="collapse navbar-collapse" id="navbarNavDropdown">-->
  <!--<ul class="navbar-nav ml-auto">-->
  <li class="nav-item">
  <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
  </li>
  <li class="nav-item">
  <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
  </li>
   <li class="nav-item">
  <%= link_to "sign Up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
  </li>
   <li class="nav-item">
  <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
  </li>
  <% end %>
  </ul>
  </div>
  </div>
  </nav>
</header>
<%= yield %>
<footer>
<div class="container mt-5">
<div class="row">
<div class="mx-auto">
<p>CopyRight Infratop.inc</p>
</div>
</div>
</div>
</footer>
</body>
</html>